version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  server:
    build: ./server
    container_name: server
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/nss-db
      - PORT=5001
      - JWT_SECRET=bs47pzic028
      - EMAIL_USER=connect2nss@gmail.com
      - EMAIL_PASS=szzq irxu ryul jbwe
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - FRONTEND_URL=http://localhost:5173
      - CLIENT=http://localhost:5173
    restart: always
    ports:
      - "5001:5001"
    working_dir: /app
    command: ["npm", "run", "start"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  react-frontend:
    build: ./client
    container_name: react-frontend
    depends_on:
      - server
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["yarn", "dev"]
